apiVersion: v1
kind: Secret
metadata:
  name: 12mcsdf-secret
  namespace: 12mcsdf
type: Opaque
data:
  rootpassword: ${{secret.ROOTPASSWORD}} | base64
  userpassword: ${{secret.USERPASSWORD}} | base64
